pre-commit:
  parallel: true
  commands:
    gofmt:
      stage_fixed: true
      glob: "*.go"
      run: gofmt -w .

    govet:
      run: go vet ./...

    gomodtidy:
      stage_fixed: true
      run: go mod tidy

pre-push:
  parallel: false
  commands:
    govulncheck:
      run: go tool govulncheck ./...
