// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"time"

	"github.com/google/uuid"
)

type Session struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Token     string
	UserAgent string
	ClientIP  string
	ExpiresAt time.Time
	RevokedAt *time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID         uuid.UUID
	Username   string
	Email      string
	Password   string
	FirstName  string
	LastName   string
	Role       string
	Status     string
	VerifiedAt *time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
}
